services:
  mongo:
    image: mongo:8
    container_name: mongodb
    hostname: mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE_TEST=${MONGO_DATABASE_TEST}
      - MONGO_USER_TEST=${MONGO_USER_TEST}
      - MONGO_PASSWORD_TEST=${MONGO_PASSWORD_TEST}
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
